# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100)),
                ('pprice', models.IntegerField(default=0)),
                ('pimage', models.ImageField(upload_to='static/images')),
                ('pdiscription', models.TextField(blank=True, default='')),
            ],
        ),
    ]
