# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-06 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pdiscription',
            field=models.TextField(blank=True, default='', verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pimage',
            field=models.ImageField(upload_to='static/images', verbose_name='商品照片'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pname',
            field=models.CharField(default='', max_length=100, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pprice',
            field=models.IntegerField(default=0, verbose_name='商品價格'),
        ),
    ]
