# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201106_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pimage',
            field=models.CharField(default='', max_length=100, verbose_name='商品照片'),
        ),
    ]
