# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-07 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201106_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='pdiscription',
            new_name='pdescription',
        ),
    ]
