# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='pname',
            field=models.CharField(default='', max_length=100, verbose_name='商品名稱'),
        ),
    ]
