# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cartmodel_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=16, verbose_name='訂單編號')),
                ('productid', models.CharField(max_length=16, verbose_name='購買商品id')),
                ('userid', models.CharField(max_length=16, verbose_name='用戶id')),
                ('userphone', models.CharField(blank=True, default='', max_length=50, verbose_name='用戶手機')),
                ('useraddr', models.CharField(blank=True, default='', max_length=255, verbose_name='用戶地址')),
                ('useremail', models.EmailField(blank=True, default='', max_length=100, verbose_name='用戶信箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='訂單成立時間')),
            ],
        ),
    ]
