# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='productid',
            field=models.CharField(max_length=625, verbose_name='購買商品id'),
        ),
    ]
