# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201110_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='userid',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='用戶名稱'),
        ),
    ]
